### ISSUE TITLE
Problem building examples

### ISSUE THREAD

**Issue by jkleiser** [aturley/osc-pony#6]
I’d like to try your osc-pony, but for some reason I have trouble building the examples. This is what happens:

```
$ ponyc examples/receive/
Building builtin -> /Volumes/P3/ponyc/packages/builtin
Building examples/receive/ -> /Volumes/P3/Pony/osc-pony/examples/receive
Building net -> /Volumes/P3/ponyc/packages/net
Building collections -> /Volumes/P3/ponyc/packages/collections
Building ponytest -> /Volumes/P3/ponyc/packages/ponytest
Building time -> /Volumes/P3/ponyc/packages/time
Error:
../src/osc-pony: couldn't locate this path
Error:
/Volumes/P3/Pony/osc-pony/examples/receive/receive.pony:9:1: can't load package '../src/osc-pony'
use "../src/osc-pony"
^
```

Doing `ponyc examples/send/` gives similar Error.

By the way, your README.md says `ponyc send/send/`.

**Comment by jkleiser** [comment]
I’m using ponyc 0.2.1-836-gf22896f on a Mac (OSX 10.11.4).

**Comment by aturley** [comment]
Ah, sorry about that. @SeanTAllen and I moved some things around last night, and we probably missed something. I'll take a look.

**Comment by aturley** [comment]
OK, I pushed the fix, it should work now.

**Comment by jkleiser** [comment]
Thanks a lot! Works fine. ;-)
